Added init support for sha/md5 verify

diff --git a/packages/WestleyR/list-files b/packages/WestleyR/list-files
--- a/packages/WestleyR/list-files
+++ b/packages/WestleyR/list-files
@@ -7,11 +7,35 @@ set -ex
 USR_NAME="WestleyR"
 PKG_NAME="list-files"
 BINARY_NAME="lf"
-PKG_VERSION="1.2.2"
+PKG_VERSION="1.3.0"
+SHA_256="4752f62a4109182ff258284cdf9f6451cc1b72db5928ceb02579aad9d4f566c4"
+MD5_SUM="65f475b3d1083b8643f626be9b4bfb38"
+SSUM=""
 
 # Download the package
 mkdir -p ${HOME}/.gpack/installed/${USR_NAME}/${PKG_NAME}
 wget -O ${HOME}/.gpack/installed/${USR_NAME}/${PKG_NAME}/package.tar.gz https://github.com/${USR_NAME}/${PKG_NAME}/archive/v${PKG_VERSION}.tar.gz
+
+# Verify the shasum
+checksum_cmd=`command -v sha256sum || command -v shasum -a256 || true`
+if ! test -n $checksum_cmd; then
+    if test -n $SHA_256; then
+        echo "Failed to find sha256sum, or shasum command. Skipping shasum"
+    fi
+else
+    echo "${SHA_256} ${HOME}/.gpack/installed/${USR_NAME}/${PKG_NAME}/package.tar.gz" | $checksum_cmd -c
+fi
+
+# Verify the md5sum
+checksum_cmd=`command -v md5sum || true`
+if ! test -n $checksum_cmd; then
+    if test -n $MD5_SUM; then
+        echo "Failed to find md5sum command. Skipping md5sum"
+    fi
+else
+    echo "${MD5_SUM} ${HOME}/.gpack/installed/${USR_NAME}/${PKG_NAME}/package.tar.gz" | $checksum_cmd -c
+fi
+
 tar -xf ${HOME}/.gpack/installed/${USR_NAME}/${PKG_NAME}/package.tar.gz -C ${HOME}/.gpack/installed/${USR_NAME}/${PKG_NAME}
 
 cd ${HOME}/.gpack/installed/${USR_NAME}/${PKG_NAME}/${PKG_NAME}-${PKG_VERSION}
