Added srm pkg + fixed precompiled dep issue

diff --git a/cmd/gpack-installer b/cmd/gpack-installer
--- a/cmd/gpack-installer
+++ b/cmd/gpack-installer
@@ -1,9 +1,9 @@
 #!/bin/bash
 # Created by: WestleyR
 # email: westleyr@nym.hush.com
-# Date: Dec 15, 2019
+# Date: Dec 18, 2019
 # https://github.com/WestleyR/gpack
-# version-1.3.2
+# version-1.0.0
 #
 # The Clear BSD License
 #
@@ -153,6 +153,16 @@ else
 fi
 
 if [ ! -z "${PREBUILT_URL}" ]; then
+  if [ ! -z "${DEP_PKGS}" ]; then
+    echo "I: Installing dependencies: ${DEP_PKGS}..."
+    for d in ${DEP_PKGS}; do
+      if ! gpack install $d ; then
+        echo "ERROR: Failed to install deps: ${d}"
+        exit 1
+      fi
+    done
+  fi
+
   echo "I: Installing prebuilt binaries..."
   if ! wget -q --show-progress -O ${gpack_prefix}/package.tar.gz ${PREBUILT_URL} ; then
     echo "ERROR: failed to download tarball from: ${PREBUILT_URL}"
