Support for single file scripts

diff --git a/cmd/gpack-installer b/cmd/gpack-installer
--- a/cmd/gpack-installer
+++ b/cmd/gpack-installer
@@ -1,13 +1,17 @@
 #!/bin/bash
 # Created by: WestleyR
-# email: westleyr@nym.hush.com
-# Date: Dec 21, 2019
+# Email(s): westleyr@nym.hush.com
+# Last modifyed date: Jan 31, 2020
+# This file version-1.0.0
+#
+# This file is part of the gpack software:
 # https://github.com/WestleyR/gpack
-# version-1.0.0
+#
+# Which that software and this file is licensed under:
 #
 # The Clear BSD License
 #
-# Copyright (c) 2019 WestleyR
+# Copyright (c) 2019-2020 WestleyR
 # All rights reserved.
 #
 # This software is licensed under a Clear BSD License.
@@ -22,29 +26,46 @@ fi
 
 build_release() {
   echo "I: Compiling from release..."
-  if ! wget -q --show-progress -O ${gpack_prefix}/package.tar.gz ${TARBALL} ; then
-    echo "ERROR: failed to download tarball from: ${TARBALL}"
-    exit 1
+  if [ -z "${TARBALL}" ]; then
+    if [ -z "${RAW_FILE}" ]; then
+      echo "ERROR: nothing to download; please open a issue at: ${USERNAME}/${PKG_NAME}"
+      exit 1
+    fi
+    packagefile="${NAME}"
+    raw_file=1
+    if ! wget -q --show-progress -O ${gpack_prefix}/${packagefile} ${RAW_FILE} ; then
+      echo "ERROR: failed to download tarball from: ${RAW_FILE}"
+      exit 1
+    fi
+  else
+    packagefile="package.tar.gz"
+    if ! wget -q --show-progress -O ${gpack_prefix}/${packagefile} ${TARBALL} ; then
+      echo "ERROR: failed to download tarball from: ${TARBALL}"
+      exit 1
+    fi
   fi
 
   if [ ! -z "${SHA256SUM}" ]; then
     if ! command -v sha256sum > /dev/null; then
       echo "WARNING: sha256sum command not found; skipping"
     else
-      if ! echo "${SHA256SUM}  ${gpack_prefix}/package.tar.gz" | sha256sum -c > /dev/null; then
+      if ! echo "${SHA256SUM}  ${gpack_prefix}/${packagefile}" | sha256sum -c > /dev/null; then
         echo "ERROR: sha256sum verify failed; hashes differ"
         exit 1
       else
-        echo "${gpack_prefix}/package.tar.gz sha256sum OK"
+        echo "${gpack_prefix}/${packagefile} sha256sum OK"
       fi
     fi
   else
-    echo "WARNING: No sha256sum to verify with..."
+    echo "WARNING: ${gpack_prefix}/${packagefile} unverifyied"
   fi
 
-  tar -xf ${gpack_prefix}/package.tar.gz -C ${gpack_prefix}
-
-  cd ${gpack_prefix}/${UNTAR_DIR}
+  if [ -z "$raw_file" ]; then
+    tar -xf ${gpack_prefix}/package.tar.gz -C ${gpack_prefix}
+    cd ${gpack_prefix}/${UNTAR_DIR}
+  else
+    cd ${gpack_prefix}
+  fi
 
   build_log=${gpack_prefix}/build.log
 
@@ -62,7 +83,7 @@ build_release() {
     # Use 'sh -c' so we can have '&&' in the install command
     if ! sh -c "${INSTALL_CMD}" &> ${build_log} ; then
       echo
-      echo "ERROR: failed to compile libraries"
+      echo "ERROR: failed to run install command"
       echo "last 10 lines from: ${build_log}"
       echo
       tail ${build_log}
@@ -113,11 +134,7 @@ build_release() {
       ln -f -s "${HOME}/.gpack/installed/${USR_NAME}/${NAME}/${PKG_VERSION}/include/$h" ${HOME}/.local/include
     done
 
-    if [ ! -z "$LATEST_COMMIT" ]; then
-      echo "$LATEST_COMMIT" > ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/version.gpack
-    else
-      echo $PKG_VERSION > ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/version.gpack
-    fi
+    echo $PKG_VERSION > ${HOME}/.gpack/installed/${USR_NAME}/${NAME}/version.gpack
 
     if [ ! -z "${INSTALL_NOTES}" ]; then
       echo
