Cache download packages in ~/.cache/gpack.cache

diff --git a/cmd/gpack-installer b/cmd/gpack-installer
--- a/cmd/gpack-installer
+++ b/cmd/gpack-installer
@@ -2,7 +2,7 @@
 # Created by: WestleyR
 # Email: westleyr@nym.hush.com
 # Url: https://github.com/WestleyR/gpack
-# Last modified date: 2020-05-17
+# Last modified date: 2020-07-25
 #
 # This file is licensed under the terms of
 #
@@ -44,6 +44,55 @@ verify_download() {
     fi
   else
     echo "WARNING: ${gpack_prefix}/${packagefile} unverifyied"
+  fi
+}
+
+verify_package() {
+  checksum="$1"
+  packagefile="$2"
+
+  if [ ! -z "$checksum" ]; then
+    if ! command -v sha256sum > /dev/null; then
+      echo "WARNING: sha256sum command not found; skipping"
+    else
+      if ! echo "$checksum  ${packagefile}" | sha256sum -c > /dev/null; then
+        echo "ERROR: sha256sum verify failed; hashes differ"
+        exit 1
+      else
+        echo "${packagefile} sha256sum OK"
+      fi
+    fi
+  else
+    echo "WARNING: ${packagefile} unverifyied"
+  fi
+}
+
+cache_dir=""
+download_pkg() {
+  pkg="$1" # eg. WestleyR/list-files
+  pkg_v="$2" # 1.6.0
+  pkg_url="$3"
+  pkg_sha256="$4"
+
+  cache_dir="${HOME}/.cache/gpack.cache/${pkg}/${pkg_v}"
+  mkdir -p $cache_dir
+  cache_dir="${cache_dir}/package.tar.gz"
+
+  # First, check if we already cached the file
+  if ! test -f $cache_dir ; then
+    echo "I: Donwload package..."
+    if ! wget -q --show-progress -O $cache_dir $pkg_url ; then
+      echo "ERROR: failed to download tarball from: $pkg_url"
+      echo "Trying to build from source..."
+      build_source
+      exit 0
+    fi
+  else
+    echo "I: Using cached file: ${cache_dir}"
+  fi
+
+  if [ ! -z "$pkg_sha256" ]; then
+    verify_package $pkg_sha256 $cache_dir
   fi
 }
 
@@ -156,36 +205,39 @@ install_files() {
   fi
 }
 
-build_master() {
-  echo "I: Compiling from release..."
+build_source() {
+  echo "I: Compiling from source..."
   if [ -z "${TARBALL}" ]; then
     if [ -z "${RAW_FILE}" ]; then
       echo "ERROR: nothing to download; please open a issue at: ${USERNAME}/${PKG_NAME}"
       exit 1
     fi
-    packagefile="${NAME}"
-    raw_file=1
-    if ! wget -q --show-progress -O ${gpack_prefix}/${packagefile} ${RAW_FILE} ; then
-      echo "ERROR: failed to download tarball from: ${RAW_FILE}"
-      exit 1
-    fi
-  else
-    packagefile="package.tar.gz"
-    if ! wget -q --show-progress -O ${gpack_prefix}/${packagefile} ${TARBALL} ; then
-      echo "ERROR: failed to download tarball from: ${TARBALL}"
-      exit 1
-    fi
   fi
 
-  # Verify the download
-  verify_download ${packagefile}
+  # TODO: fix somthing with single file install
+#  url="${TARBALL}"
+#  if [ ! -z "${RAW_FILE}" ]; then
+#    echo "I: Installing single file..."
+#
+#    url="${RAW_FILE}"
+#
+#    packagefile="${NAME}"
+#    raw_file=1
+#  fi
 
-  if [ -z "$raw_file" ]; then
-    tar -xf ${gpack_prefix}/package.tar.gz -C ${gpack_prefix}
-    cd ${gpack_prefix}/${UNTAR_DIR}
-  else
-    cd ${gpack_prefix}
-  fi
+  # Download the package, or used the cached one
+  download_pkg "${USR_NAME}/${PKG_NAME}" "${PKG_VERSION}" "${TARBALL}" ${SHA256SUM}
+
+
+#  if [ -z "$raw_file" ]; then
+#    tar -xf ${gpack_prefix}/package.tar.gz -C ${gpack_prefix}
+#    cd ${gpack_prefix}/${UNTAR_DIR}
+#  else
+#    cd ${gpack_prefix}
+#  fi
+
+  tar -xf $cache_dir -C ${gpack_prefix}
+  cd ${gpack_prefix}/${UNTAR_DIR}
 
   # Install the deps (if any)
   install_deps ${DEP_PKGS}
@@ -213,7 +265,8 @@ build_master() {
   exit 0
 }
 
-build_release() {
+build_compiled() {
+  echo "I: Installing prebuilt binaries..."
   if [ ! -z "${PREBUILT_URL}" ]; then
     if [ ! -z "${DEP_PKGS}" ]; then
       echo "I: Installing dependencies: ${DEP_PKGS}..."
@@ -225,38 +278,17 @@ build_release() {
       done
     fi
 
-    echo "I: Installing prebuilt binaries..."
-    if ! wget -q --show-progress -O ${gpack_prefix}/package.tar.gz ${PREBUILT_URL} ; then
-      echo "ERROR: failed to download tarball from: ${PREBUILT_URL}"
-      echo "Trying to build from master..."
-      build_master
-      exit 0
-    fi
-    if [ ! -z "${PREBUILT_SHA256SUM}" ]; then
-      if ! command -v sha256sum > /dev/null; then
-        echo "WARNING: sha256sum command not found; skipping"
-      else
-        if ! echo "${PREBUILT_SHA256SUM}  ${gpack_prefix}/package.tar.gz" | sha256sum -c > /dev/null; then
-          echo "ERROR: sha256sum verify failed; hashes differ"
-          build_master
-          exit 0
-        else
-          echo "${gpack_prefix}/package.tar.gz sha256sum OK"
-        fi
-      fi
-    else
-      echo "WARNING: No sha256sum to verify with..."
-    fi
+    # Download the package, or used the cached one
+    download_pkg "${USR_NAME}/${PKG_NAME}" "${PKG_VERSION}" "${PREBUILT_URL}" ${PREBUILT_SHA256SUM}
 
     mkdir -p ${HOME}/.gpack/installed/${USR_NAME}
-    tar -xf ${gpack_prefix}/package.tar.gz -C ${HOME}/.gpack/installed/${USR_NAME}
+    tar -xf $cache_dir -C ${HOME}/.gpack/installed/${USR_NAME}
 
-    echo "I: Installing files..."
     install_files
 
     exit 0
   else
-    build_master
+    build_source
   fi
 }
 
@@ -268,10 +300,10 @@ build_log=${gpack_prefix}/build.log
 if [ -z ${GPACK_ARCH} ]; then
   echo "WARNING: \$GPACK_ARCH is not set; see https://github.com/WestleyR/gpack for help"
   echo "WARNING: Cant get prebuilt binaries for a unset arch"
-  build_master
+  build_compiled
   exit 0
 elif [ ! -z ${GPACK_COMPILE_BUILD} ]; then
-  build_master
+  build_source
   exit 0
 fi
 
@@ -289,10 +321,10 @@ elif [[ "${GPACK_ARCH}" = "armv7l" ]]; then
   PREBUILT_SHA256SUM="${ARMV7L_SHA256SUM}"
 else
   echo "They are no pre-built binaries for you arch: ${GPACK_ARCH}"
-  build_master
+  build_source
   exit 0
 fi
 
-build_release
+build_compiled
 
 # vim: tabstop=2 shiftwidth=2 expandtab autoindent softtabstop=0
